### ISSUE TITLE
I HavePubilshed this to CHrome web store.

### ISSUE THREAD

**Issue by redmangospros** [kyleplo/scratch-emoji-shortcuts#1]
I Have given you credit, saying you are the offical owner. I have alos stated that i have tested this.
I still haven't pubilshed. DO you Want it?
 SHould i delate it?

**Comment by redmangospros** [comment]
it is privte as inly i can see it

**Comment by kyleplo** [comment]
Please remove it

**Comment by redmangospros** [comment]
It never went
